### ISSUE TITLE
--type=module should be --type=source-text-module

### ISSUE THREAD

**Issue by devsnek** [GeoffreyBooth/node-esm-entry-points-proposal#1]
and it should probably be --entry-type or something, since node has so many flags its good to be specific.

**Comment by GeoffreyBooth** [comment]
As I wrote in the issue presenting this, I’d prefer not to get into bikeshed discussions about names. We can have an overall UX discussion in Stage 4 about the names for everything and the shape of configuration once the full scope of our new functionality is clear.

**Comment by devsnek** [comment]
the name of the flag is a bikeshed but `module` to `source-text-module` isn't. there are multiple types of modules and that's a functionality change not just a name change. please reopen.
