### ISSUE TITLE
Should -e and stdin remain eval-based?

### ISSUE THREAD

**Issue by zenparsing** [GeoffreyBooth/node-esm-entry-points-proposal#4]
I thought a little about modifying Node's stdin and `--eval` processing to accept ESM, but ran into difficulties: Node assumes that such input can be eval'ed, basically. But ESM can't really be eval'ed.

With that in mind, do you think it might make sense to leave `--eval` and stdin script-only?

**Comment by SMotaal** [comment]
I agree with you on eval, but imho we can't generalize to `stdin` because you sometimes generate code on-the-fly and pipe it into a `child_process`. I don't do this personally, but I can't not see this being useful. Does that sound reasonable?

**Comment by zenparsing** [comment]
It might be good to gather some use cases. @jdalton: does `esm` support ESM via stdin? Did users ask for that feature?

**Comment by GeoffreyBooth** [comment]
They’re not technically script-only, they’re CommonJS; `node --eval "console.log(require('path').sep)"` works.

There is a use case for supporting ESM in `--eval` and `STDIN`, which is the one I listed in the proposal: CLI tools like `coffee` and `babel`. When you type `coffee --eval "console.log require('path').sep"` it transpiles that string to JS and then runs the `node --eval` command above. Ditto for Babel, and I assume TypeScript and others. Supporting ESM in `--eval` is what led me to join this group in the first place.

**Comment by zenparsing** [comment]
In a REPL, you'd have to do something like:

```
> console.log (await import('path')).sep
```

Would this `await import(...)` pattern be sufficient for your `--eval` use case?

**Comment by GeoffreyBooth** [comment]
> Would this `await import(...)` pattern be sufficient for your `--eval` use case?

No. `coffee file.coffee` transpiles `file.coffee` into JavaScript and executes that JS via `node --eval`, and users will expect `import` statements in files to work. I would also argue that they would expect `import` statements in `--eval` to work; `--eval` should execute any valid JavaScript, and an `import` statement is valid JavaScript. The same expectations for `coffee file.coffee` also apply to Babel, TypeScript and similar tools.

`--eval` isn’t just for debugging or experimentation the way the REPL is. It’s the primary way to provide string source code input into Node, and there are lots of other tools that generate source code for Node to execute.

**Comment by jdalton** [comment]
@zenparsing 
> does `esm` support ESM via stdin?

Yes. The `esm` loader works with`--check`, `--eval`, `--print`, and stdin eval.

> Did users ask for that feature?

Not stdin specifically.

**Comment by zenparsing** [comment]
> `coffee file.coffee` transpiles `file.coffee` into JavaScript and executes that JS via `node --eval`

I'd like to know more about the coffee use case; can you link to the source code that does this? Thanks!

**Comment by GeoffreyBooth** [comment]
> I’d like to know more about the coffee use case; can you link to the source code that does this? Thanks!

It’s here: https://github.com/jashkenas/coffeescript/blob/master/src/index.coffee#L35-L60

And . . . it doesn’t use `--eval`, it uses `require._compile`. I honestly don’t know how I’ve been misremembering this for all the time we’ve been discussing the `--eval` case. I _think_ that maybe when I tried to update CoffeeScript to use `--experimental-modules` a year or so ago I started a new branch that used `--eval`, and that’s probably what I’m remembering. My apologies.

Babel (via [`babel-node`](https://babeljs.io/docs/en/next/babel-node.html)) uses `vm.runInThisContext`:
https://github.com/babel/babel/blob/master/packages/babel-node/src/_babel-node.js#L121-L134

TypeScript doesn’t seem to have built-in evaluation support, but the [`ts-node`](https://github.com/TypeStrong/ts-node) project provides functionality similar to `babel-node`. It also uses `vm.runInThisContext`:
https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts#L229-L233

Regardless, I think that users are right to expect that code that works in `.js` or `.mjs` files should also work in `--eval`.

Thanks for asking the question though, not just to set me straight but to also illuminate a few other entry point types we need to consider, such as `vm.runInThisContext` and `--print`.

**Comment by zenparsing** [comment]
Thanks @GeoffreyBooth for digging this out - really useful info!

**Comment by GeoffreyBooth** [comment]
@zenparsing Getting back to the original question, I think it’s fair of users to expect that `import { sep } from 'path'; console.log(sep)` would work via `--eval`. Do you agree? I didn’t know until you mentioned it that `--eval` passes its input into `eval()`, I just assumed that it was evaluating input sent in via string rather than file. I feel like my assumption is probably typical of users in this regard; or rather, I think it would be much more surprising to users that `import` in `--eval` _doesn’t_ work than that it does.

So unless you disagree, can we close this issue and take the position that ESM syntax should be supported in `--eval`?

**Comment by GeoffreyBooth** [comment]
Seeing as this has already been implemented, I’m going to close this issue. I still feel like `--eval` should support ESM syntax, though I acknowledge the potential confusion of a flag named `eval` not passing its input to `eval()` 😄
